yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='create_post'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
    path('groups/', views.groups, name='groups'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='group')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста', help_text='Текст нового поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата публикации', db_index=True)
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        blank=True, null=True,
        max_length=255,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text='Загрузите картинку'
    )
    post_views = models.IntegerField(default=0)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    description = models.TextField(max_length=400)

    def __str__(self):
        return str(self.title)


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Коментарий к'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор коментария'
    )
    text = models.TextField(
        verbose_name='Текст коментария', help_text='Текст нового коментария'
    )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата публикации коментария')

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following')

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow


@cache_page(20)
def index(request):
    search = request.GET.get('search', '')
    if search:
        post_list = Post.objects.filter(text__icontains=search)
    else:
        post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.PAGE_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    group_list = group.posts.all()
    paginator = Paginator(group_list, settings.PAGE_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    count = group.posts.filter(group=group).count()
    context = {
        'group': group,
        'count': count,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def groups(request):
    group_list = Group.objects.all()
    context = {
        'group_list': group_list
    }
    return render(request, 'posts/groups.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None
                    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id, author=request.user)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post
                    )
    if form.is_valid():
        post = form.save(commit=False)
        post.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = user.posts.all()
    paginator = Paginator(posts, settings.PAGE_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    num_post = user.posts.all().count()
    following = user.following.all().exists()
    context = {
        'author': user,
        'page_obj': page_obj,
        'num_post': num_post,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    count = Post.objects.filter(author=post.author).count()
    post_object = Post.objects.get(id=post_id)
    post_object.post_views = post_object.post_views + 1
    post_object.save()
    context = {
        'post': post,
        'count': count,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:
        post.delete()
    else:
        return redirect('users:login')
    return redirect('posts:profile', username=request.user)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, settings.PAGE_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author == request.user:
        return redirect('posts:profile', username=request.user)
    Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    obj = Follow.objects.get(
        user=request.user, author=author)
    obj.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/includes/post_list.html
{% load thumbnail %}
<article>
  <div class="shadow-lg p-3 mb-5 bg-white rounded">
    <strong>
      <h3>
        {{ post.text|truncatewords:10 }}
    </strong>
    </h3>
    <p class="text-muted">
      <i>
        {{ post.pub_date|date:"d E Y" }}
      </i>
    </p>
    <strong>
      <a href="{% url 'posts:profile' post.author.username %}" class="text-decoration-none">
        @{{ post.author.username }}</a>
    </strong>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <a href="{% url 'posts:post_detail' post.pk %}"><img class="card-img my-2" src="{{ im.url }}"></a>
    {% endthumbnail %}
    <p>
    {{ post.text|truncatewords:60 }}
    </p>
    <p>
      <div class="container px-0">
        <div class="row justify-content-md-center">
          <div class="col">
            {% if post.group  %}
            <strong>
              <a href="{% url 'posts:group_list' post.group.slug %}" class="text-decoration-none">
                #{{ post.group.title }}
              </a>
            </strong>
            {% else %}
            {% endif %}
          </div>
          <div class="col-md-auto">
            <strong>
              <div class="link-read-post"><a href="{% url 'posts:post_detail' post.pk %}"
                  class="text-decoration-none text-muted"> Читать дальше...</a></div>
            </strong>
          </div>
        </div>
      </div>
      <div class="text-muted">
      <i>
      <small>
        Всего комментариев:
        {% if post.comments.count > 0 %}
        <a href="{% url 'posts:post_detail' post.id %}" id="comment_sym{{ post.id }}" class="text-decoration-none">
          <span class="text-muted" id="comment_val{{ post.id }}">{{post.comments.count}}</span>
        </a>
        {% else %}
        <a href="{% url 'posts:post_detail' post.id %}" id="comment_sym{{ post.id }}" class="text-decoration-none">
          <span class="text-muted" id="comment_val{{ post.id }}">{{post.comments.count}}</span>
        </a>
        {% endif %}
         |
        Просмотров: {{post.post_views}}
        </small>
        </i>
    </p>
  </div>
  </div>
</article>

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
    <div class="container py-2">
    <ul class="nav nav-tabs" id="nav-tab" role="tablist">
    {% with url_name=request.resolver_match.url_name %}
      <li class="nav-item">
        <a 
          class="nav-link {% if url_name == 'index' %} active {% endif %}" 
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if url_name == 'follow_index' %} active {% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if url_name == 'groups' %} active {% endif %}"
           href="{% url 'posts:groups' %}"
        >
          Сообщества
        </a>
      </li>      
      {% endwith %}
    </ul>
    </div>
{% endif %}