yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='create_post'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
    path('groups/', views.groups, name='groups'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='group')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста', help_text='Текст нового поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата публикации', db_index=True)
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        blank=True, null=True,
        max_length=255,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text='Загрузите картинку'
    )
    post_views = models.IntegerField(default=0)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    description = models.TextField(max_length=400)

    def __str__(self):
        return str(self.title)


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Коментарий к'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор коментария'
    )
    text = models.TextField(
        verbose_name='Текст коментария', help_text='Текст нового коментария'
    )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата публикации коментария')

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following')

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow


@cache_page(20)
def index(request):
    search = request.GET.get('search', '')
    if search:
        post_list = Post.objects.filter(text__icontains=search)
    else:
        post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.PAGE_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    group_list = group.posts.all()
    paginator = Paginator(group_list, settings.PAGE_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    count = group.posts.filter(group=group).count()
    context = {
        'group': group,
        'count': count,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def groups(request):
    group_list = Group.objects.all()
    context = {
        'group_list': group_list
    }
    return render(request, 'posts/groups.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None
                    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id, author=request.user)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post
                    )
    if form.is_valid():
        post = form.save(commit=False)
        post.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = user.posts.all()
    paginator = Paginator(posts, settings.PAGE_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    num_post = user.posts.all().count()
    following = user.following.all().exists()
    context = {
        'author': user,
        'page_obj': page_obj,
        'num_post': num_post,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    count = Post.objects.filter(author=post.author).count()
    post_object = Post.objects.get(id=post_id)
    post_object.post_views = post_object.post_views + 1
    post_object.save()
    context = {
        'post': post,
        'count': count,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:
        post.delete()
    else:
        return redirect('users:login')
    return redirect('posts:profile', username=request.user)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, settings.PAGE_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author == request.user:
        return redirect('posts:profile', username=request.user)
    Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    obj = Follow.objects.get(
        user=request.user, author=author)
    obj.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
{% if not post %}
Редактировать пост
{% else %}
Создать запись
{% endif %}
{% endblock %}

{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-9 p-5">
      <div class="card">
        <div class="card-header">
          {% load user_filters%}
          {% if not post %}
          Новый пост
          {% else %}
          Редактировать пост
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data"
            action={% if post %}"{% url 'posts:post_edit' post_id=post.pk %}"{% else %}"{% url 'posts:create_post' %}"{% endif %}>
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
              {% if fields.errors %}
              <div class="alert alert-danger">
                {{ fields.errors }}
              </div>
              {% endif %}
              {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              {{ field|addclass:"form-control" }}
              {% if field.help_text %}
              <p class="form-text text-muted">{{ field.help_text }}</p>
              {% endif %}
            </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if post %}
                Сохранить
                {% else %}
                Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Избранные посты авторов, на которых вы подписаны.{% endblock %}
{% block header %}
 <h1>Избранные посты авторов, на которых вы подписаны</h1> 
 <hr>
 {% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
{% include 'posts/includes/post_list.html' %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ group.title }}{% endblock %}
{% block header %}<h1>«{{ group.title }}»</h1>{% endblock %} 
{% block content %}
<p>{{ group.description }}</p>
<small class="text-muted fs-6">Всего постов в группе: {{ count }}</small> 
<hr>
{% for post in page_obj %}
{% include 'posts/includes/post_list.html' %}
{% endfor %} 
{% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/groups.html
{% extends 'base.html' %}
{% block title %}Сообщества{% endblock %}
{% block header %}
 <h1>Сообщества</h1> 
 <hr>
 {% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% for group in group_list %}
<div class="container">
    <div class="card mb-3 mt-1 shadow-sm">
        <div class="media-body card-body">
            <h5 class="mt-0">                
                <a href="{% url 'posts:group_list' group.slug %}" class="text-decoration-none">
                {{ group.title }}
                </a>
            </h5>
            <small class="text-muted">{{ group.description }}</small>
        </div>
    </div>
</div>    
{% endfor %}
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте.{% endblock %}
{% block header %}
 <h1>Последние обновления на сайте </h1> 
 <hr>
 {% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
  {% include 'posts/includes/post_list.html' %}
  {% endfor %} 
{% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}
Пост {{ post.text|truncatewords:30 }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <div class="card">
        <div class="card-body">
          <ul class="list-group list-group-flush ">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            <li class="list-group-item">
              Всего комментариев:
              {% if post.comments.count > 0 %}
              <a href="{% url 'posts:post_detail' post.id %}" id="comment_sym{{ post.id }}"
                class="badge btn-info float-left mr-2 text-decoration-none text-dark">
                <span id="comment_val{{ post.id }}">{{post.comments.count}}</span>
              </a>
              {% else %}
              <a href="{% url 'posts:post_detail' post.id %}" id="comment_sym{{ post.id }}"
                class="badge btn-secondary float-left mr-2 text-decoration-none">
                <span id="comment_val{{ post.id }}">{{post.comments.count}}</span>
              </a>
              {% endif %}
            </li>
            <li class="list-group-item">
              Просмотры : {{post.post_views}}
            </li>
            {% if post.group  %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              {% else %}
              {% endif %}
              {% if post.group  %}
              <p><a href="{% url 'posts:group_list' post.group.slug %}" class="text-decoration-none">все записи
                  группы</a></p>
              {% else %}
              {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: <span class="badge bg-info text-dark"> {{ count }} </span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}" class="text-decoration-none">
                все посты пользователя
              </a>
            </li>
          </ul>
        </div>
      </div>
    </aside>
    <article class="col-12 col-md-9">
      <h2>{{ post.text|truncatewords:10 }}</h2>
      <hr>
      {% thumbnail post.image "960x500" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        <h6>
          {{ post.text|linebreaks}}
        </h6>
      </p>
      <hr>
      {% if post.author == user %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">Редактировать запись</a>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Удалить запись
      </button>
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Вы точно хотите удалить запись?</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Нет</button>
              <a class="btn btn-primary" href="{% url 'posts:post_delete' post.pk %}">Да</a>
            </div>
          </div>
        </div>
      </div>
      {% else %}
      {% endif %}
      {% if user.is_authenticated %}
      <div class="card my-4">
        <h6 class="card-header">Добавить комментарий:</h6>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}
            <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
      {% endif %}
      <h3>Комментарии</h3>
      {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <div class="row justify-content-md-center">
            <div class="col">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}" class="text-decoration-none">
                  {{ comment.author.username }}
                </a>
              </h5>
            </div>
            <div class="col-md-auto">
              <i>
                <small class="text-muted">{{ comment.created|date:"d E Y" }}</small>
              </i>
            </div>
          </div>
          <p>
            {{ comment.text }}
          </p>
          <hr>
          {% endfor %}
    </article>
  </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Профайл пользователя {{ author.username }}
{% endblock %}
{% block content %}
<div class="mb-5">
  <p>
    <h1> Все посты пользователя {{ author.get_full_name }} </h1>
  </p>
  <p>
    <h3>Всего постов: {{ num_post }} </h3>
  </p>
  <hr>
  {% if request.user !=  author  %}
  {% if following %}
  <a class="btn btn-lg btn-light" href="{% url 'posts:profile_unfollow' author.username %}" role="button">
    Отписаться
  </a>
  {% else %}
  <a class="btn btn-lg btn-primary" href="{% url 'posts:profile_follow' author.username %}" role="button">
    Подписаться
  </a>
  {% endif %}
  {% endif %}
</div>
{% for post in page_obj %}
{% include 'posts/includes/post_list.html' %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}